"""
ComfyUI PNG Metadata Reader Node
Reads workflow prompt from PNG images generated by ComfyUI

IMPORTANT: Use the file path input, not IMAGE tensor!
The IMAGE tensor loses metadata during conversion.
"""

import json
import os
from PIL import Image
import numpy as np
import torch
import folder_paths


class LoadImageWithMetadata:
    """
    Load image AND preserve its metadata.
    This is the recommended way to read PNG metadata in ComfyUI.
    """

    CATEGORY = "Image Utilities"

    def __init__(self):
        pass

    @classmethod
    def INPUT_TYPES(s):
        input_dir = folder_paths.get_input_directory()
        files = [f for f in os.listdir(input_dir) if f.lower().endswith(('.png', '.jpg', '.jpeg', '.webp'))]
        return {
            "required": {
                "image": (sorted(files),),
            },
        }

    RETURN_TYPES = ("IMAGE", "STRING", "STRING", "STRING")
    RETURN_NAMES = ("image", "workflow_prompt", "workflow_ui", "raw_metadata")
    FUNCTION = "load_image"
    OUTPUT_NODE = True

    def load_image(self, image):
        """
        Load image and extract metadata.
        """
        input_dir = folder_paths.get_input_directory()
        image_path = os.path.join(input_dir, image)

        # Load image as tensor
        img = Image.open(image_path)
        img_array = np.array(img).astype(np.float32) / 255.0
        image_tensor = torch.from_numpy(img_array)[None,]

        # Extract metadata
        workflow_prompt = "No workflow prompt found."
        workflow_ui = "No workflow UI found."
        raw_metadata = "{}"

        try:
            metadata = img.info
            raw_metadata = json.dumps(metadata, indent=2, default=str)

            if "prompt" in metadata:
                try:
                    parsed = json.loads(metadata["prompt"])
                    workflow_prompt = json.dumps(parsed, indent=2)
                except json.JSONDecodeError:
                    workflow_prompt = metadata["prompt"]

            if "workflow" in metadata:
                try:
                    parsed = json.loads(metadata["workflow"])
                    workflow_ui = json.dumps(parsed, indent=2)
                except json.JSONDecodeError:
                    workflow_ui = metadata["workflow"]

        except Exception as e:
            workflow_prompt = f"Error reading metadata: {e}"

        return (image_tensor, workflow_prompt, workflow_ui, raw_metadata)


class PNGMetadataFromPath:
    """
    Read metadata from a file path string.
    Use this when you have the file path, not an IMAGE tensor.
    """

    CATEGORY = "Image Utilities"

    def __init__(self):
        pass

    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "file_path": ("STRING", {"default": ""}),
            },
        }

    RETURN_TYPES = ("STRING", "STRING", "STRING")
    RETURN_NAMES = ("workflow_prompt", "workflow_ui", "raw_metadata")
    FUNCTION = "read_metadata"
    OUTPUT_NODE = True

    def read_metadata(self, file_path):
        """
        Read PNG metadata from file path.
        """
        workflow_prompt = "No workflow prompt found."
        workflow_ui = "No workflow UI found."
        raw_metadata = "{}"

        if not file_path or not os.path.exists(file_path):
            return (f"File not found: {file_path}", "", "")

        try:
            with Image.open(file_path) as img:
                metadata = img.info
                raw_metadata = json.dumps(metadata, indent=2, default=str)

                if "prompt" in metadata:
                    try:
                        parsed = json.loads(metadata["prompt"])
                        workflow_prompt = json.dumps(parsed, indent=2)
                    except json.JSONDecodeError:
                        workflow_prompt = metadata["prompt"]

                if "workflow" in metadata:
                    try:
                        parsed = json.loads(metadata["workflow"])
                        workflow_ui = json.dumps(parsed, indent=2)
                    except json.JSONDecodeError:
                        workflow_ui = metadata["workflow"]

        except Exception as e:
            workflow_prompt = f"Error reading file: {e}"

        return (workflow_prompt, workflow_ui, raw_metadata)


class ExtractPromptValues:
    """
    Extract specific values from workflow prompt JSON.
    Parse the workflow to find positive/negative prompts, seed, steps, etc.
    """

    CATEGORY = "Image Utilities"

    def __init__(self):
        pass

    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "workflow_prompt": ("STRING", {"default": ""}),
            },
        }

    RETURN_TYPES = ("STRING", "STRING", "INT", "INT", "FLOAT", "STRING")
    RETURN_NAMES = ("positive_prompt", "negative_prompt", "seed", "steps", "cfg", "model_name")
    FUNCTION = "extract"
    OUTPUT_NODE = True

    def extract(self, workflow_prompt):
        """
        Extract specific values from workflow JSON.
        """
        positive_prompt = ""
        negative_prompt = ""
        seed = 0
        steps = 0
        cfg = 0.0
        model_name = ""

        try:
            workflow = json.loads(workflow_prompt)

            for node_id, node_data in workflow.items():
                class_type = node_data.get("class_type", "")
                inputs = node_data.get("inputs", {})

                # KSampler / KSamplerAdvanced
                if "KSampler" in class_type:
                    seed = inputs.get("seed", inputs.get("noise_seed", 0))
                    steps = inputs.get("steps", 0)
                    cfg = inputs.get("cfg", 0.0)

                # CLIPTextEncode - find prompts
                if class_type == "CLIPTextEncode":
                    text = inputs.get("text", "")
                    # Check widget_values for title hint
                    widgets = node_data.get("widgets_values", [])
                    if text:
                        if not positive_prompt:
                            positive_prompt = text
                        elif text != positive_prompt:
                            negative_prompt = text

                # PrimitiveString / PrimitiveStringMultiline
                if "PrimitiveString" in class_type:
                    text = inputs.get("value", inputs.get("text", ""))
                    widgets = node_data.get("widgets_values", [])
                    if text and len(text) > 10:
                        if not positive_prompt:
                            positive_prompt = text
                        elif text != positive_prompt:
                            negative_prompt = text

                # Model loaders
                if "CheckpointLoader" in class_type:
                    model_name = inputs.get("ckpt_name", "")
                elif "UNETLoader" in class_type:
                    model_name = inputs.get("unet_name", "")

        except json.JSONDecodeError:
            pass
        except Exception as e:
            positive_prompt = f"Error: {e}"

        return (positive_prompt, negative_prompt, int(seed), int(steps), float(cfg), model_name)


# Register nodes
NODE_CLASS_MAPPINGS = {
    "LoadImageWithMetadata": LoadImageWithMetadata,
    "PNGMetadataFromPath": PNGMetadataFromPath,
    "ExtractPromptValues": ExtractPromptValues,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "LoadImageWithMetadata": "Load Image (With Metadata)",
    "PNGMetadataFromPath": "Read PNG Metadata (Path)",
    "ExtractPromptValues": "Extract Prompt Values",
}
