"""
ComfyUI PNG Metadata Reader Node
Reads workflow prompt from PNG images generated by ComfyUI
"""

import io
import json
from PIL import Image
import numpy as np
import torch


class PNGMetadataReader:
    """
    A ComfyUI node that reads and extracts workflow prompts
    embedded in PNG image metadata.
    """

    CATEGORY = "Image Utilities"

    def __init__(self):
        pass

    @classmethod
    def INPUT_TYPES(s):
        """
        Defines the input types and widgets for the node.
        """
        return {
            "required": {
                "image": ("IMAGE",),
            },
        }

    RETURN_TYPES = ("STRING", "STRING", "STRING")
    RETURN_NAMES = ("workflow_prompt", "workflow_ui", "raw_metadata")
    FUNCTION = "read_metadata"

    def read_metadata(self, image):
        """
        Read PNG metadata and extract workflow information.

        Args:
            image: ComfyUI IMAGE tensor (batch of images)

        Returns:
            Tuple of (workflow_prompt, workflow_ui, raw_metadata)
        """
        # ComfyUI image tensor is usually a batch. We'll take the first image.
        if isinstance(image, torch.Tensor):
            # Convert the torch tensor to a PIL Image
            # ComfyUI tensors are typically float32 [0, 1] and RGB or RGBA
            # We need to convert to uint8 for Pillow
            image_np = image[0].cpu().numpy()  # Get the first image in the batch
            image_np_255 = (image_np * 255).astype(np.uint8)

            # Determine mode based on channels (e.g., RGB for 3, RGBA for 4)
            if image_np_255.shape[2] == 3:
                mode = "RGB"
            elif image_np_255.shape[2] == 4:
                mode = "RGBA"
            else:
                return ("Error: Unsupported image channel count.", "", "")

            img_pil = Image.fromarray(image_np_255, mode)
        else:
            return ("Error: Input is not a valid image tensor.", "", "")

        workflow_prompt = "No workflow prompt found."
        workflow_ui = "No workflow UI found."
        raw_metadata = ""

        try:
            # Get all metadata from the image
            # ComfyUI and Automatic1111 store metadata in tEXt chunks
            metadata = img_pil.info

            # Format raw metadata for display
            raw_metadata = json.dumps(metadata, indent=2, default=str)

            # Extract 'prompt' (workflow JSON)
            if "prompt" in metadata:
                json_data = metadata["prompt"]
                try:
                    parsed_json = json.loads(json_data)
                    workflow_prompt = json.dumps(parsed_json, indent=2)
                except json.JSONDecodeError:
                    workflow_prompt = f"Found 'prompt' metadata, but it's not valid JSON:\n{json_data}"

            # Extract 'workflow' (UI layout)
            if "workflow" in metadata:
                json_data = metadata["workflow"]
                try:
                    parsed_json = json.loads(json_data)
                    workflow_ui = json.dumps(parsed_json, indent=2)
                except json.JSONDecodeError:
                    workflow_ui = f"Found 'workflow' metadata, but it's not valid JSON:\n{json_data}"

        except Exception as e:
            workflow_prompt = f"An error occurred while reading metadata: {e}"

        return (workflow_prompt, workflow_ui, raw_metadata)


class PNGMetadataExtractor:
    """
    Advanced node that extracts specific values from the workflow prompt.
    """

    CATEGORY = "Image Utilities"

    def __init__(self):
        pass

    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "image": ("IMAGE",),
            },
        }

    RETURN_TYPES = ("STRING", "STRING", "INT", "INT", "STRING")
    RETURN_NAMES = ("positive_prompt", "negative_prompt", "seed", "steps", "model_name")
    FUNCTION = "extract_values"

    def extract_values(self, image):
        """
        Extract specific values from the workflow JSON.

        Returns:
            Tuple of (positive_prompt, negative_prompt, seed, steps, model_name)
        """
        positive_prompt = ""
        negative_prompt = ""
        seed = 0
        steps = 0
        model_name = ""

        # Convert tensor to PIL Image
        if isinstance(image, torch.Tensor):
            image_np = image[0].cpu().numpy()
            image_np_255 = (image_np * 255).astype(np.uint8)

            if image_np_255.shape[2] == 3:
                mode = "RGB"
            elif image_np_255.shape[2] == 4:
                mode = "RGBA"
            else:
                return ("", "", 0, 0, "")

            img_pil = Image.fromarray(image_np_255, mode)
        else:
            return ("", "", 0, 0, "")

        try:
            metadata = img_pil.info

            if "prompt" in metadata:
                workflow = json.loads(metadata["prompt"])

                # Parse nodes to find specific values
                for node_id, node_data in workflow.items():
                    class_type = node_data.get("class_type", "")
                    inputs = node_data.get("inputs", {})

                    # Find KSampler for seed and steps
                    if "KSampler" in class_type:
                        seed = inputs.get("seed", 0)
                        steps = inputs.get("steps", 0)

                    # Find positive prompt
                    if "CLIPTextEncode" in class_type:
                        text = inputs.get("text", "")
                        if text and not positive_prompt:
                            positive_prompt = text
                        elif text and positive_prompt and text != positive_prompt:
                            negative_prompt = text

                    # Find model loader
                    if "CheckpointLoader" in class_type or "UNETLoader" in class_type:
                        model_name = inputs.get("ckpt_name", inputs.get("unet_name", ""))

        except Exception as e:
            positive_prompt = f"Error: {e}"

        return (positive_prompt, negative_prompt, seed, steps, model_name)


# Register nodes
NODE_CLASS_MAPPINGS = {
    "PNGMetadataReader": PNGMetadataReader,
    "PNGMetadataExtractor": PNGMetadataExtractor,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "PNGMetadataReader": "Read PNG Workflow Prompt",
    "PNGMetadataExtractor": "Extract PNG Values",
}
