"""
ComfyUI PNG Metadata Reader Node
Reads workflow prompt from PNG images generated by ComfyUI

Features:
- Batch Simple Readable Metadata - Read metadata from entire folder
- Simple Readable Metadata (KJ) - For KJ nodes
- Batch process images from folder
- Extract prompts, seed, steps, cfg, model
"""

import json
import os
import glob
from PIL import Image
import numpy as np
import torch
import folder_paths

# Import the batch folder reader
from .folder_metadata_reader import BatchSimpleReadableMetadata
from .kj_metadata_reader import SimpleReadableMetadataKJ


class BatchMetadataReader:
    """
    Batch read metadata from all images in a folder.
    """

    CATEGORY = "Image Utilities"

    def __init__(self):
        pass

    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "folder_path": ("STRING", {"default": "", "multiline": False}),
                "file_pattern": ("STRING", {"default": "*.png"}),
                "recursive": ("BOOLEAN", {"default": False}),
            },
        }

    RETURN_TYPES = ("STRING", "STRING", "INT")
    RETURN_NAMES = ("all_metadata", "summary", "file_count")
    FUNCTION = "read_batch"
    OUTPUT_NODE = True

    def read_batch(self, folder_path, file_pattern="*.png", recursive=False):
        if not folder_path or not os.path.isdir(folder_path):
            return (f"Error: Folder not found: {folder_path}", "", 0)

        if recursive:
            files = glob.glob(os.path.join(folder_path, "**", file_pattern), recursive=True)
        else:
            files = glob.glob(os.path.join(folder_path, file_pattern))

        if not files:
            return (f"No files matching '{file_pattern}' in {folder_path}", "", 0)

        all_metadata = {}
        summary_lines = []
        positive_prompts = []
        negative_prompts = []
        models = set()
        loras = set()

        for file_path in sorted(files):
            filename = os.path.basename(file_path)
            file_data = {
                "filename": filename,
                "path": file_path,
                "metadata": {},
                "prompt": None,
                "workflow": None
            }

            try:
                with Image.open(file_path) as img:
                    metadata = img.info
                    file_data["metadata"] = dict(metadata)

                    if "prompt" in metadata:
                        try:
                            prompt_data = json.loads(metadata["prompt"])
                            file_data["prompt"] = prompt_data
                            extracted = self._extract_values(prompt_data)
                            file_data["extracted"] = extracted

                            if extracted["positive_prompt"]:
                                positive_prompts.append({
                                    "file": filename,
                                    "text": extracted["positive_prompt"]
                                })
                            if extracted["negative_prompt"]:
                                negative_prompts.append({
                                    "file": filename,
                                    "text": extracted["negative_prompt"]
                                })
                            if extracted["model_name"]:
                                models.add(extracted["model_name"])
                            if extracted.get("loras"):
                                for lora in extracted["loras"]:
                                    loras.add(lora)
                        except json.JSONDecodeError:
                            pass

                    if "workflow" in metadata:
                        try:
                            file_data["workflow"] = json.loads(metadata["workflow"])
                        except json.JSONDecodeError:
                            pass
            except Exception as e:
                file_data["error"] = str(e)

            all_metadata[filename] = file_data

        summary_lines.append(f"=== Batch Metadata Summary ===")
        summary_lines.append(f"Folder: {folder_path}")
        summary_lines.append(f"Files processed: {len(files)}")
        summary_lines.append(f"")
        summary_lines.append(f"=== Models Used ===")
        for m in sorted(models):
            summary_lines.append(f"  - {m}")
        summary_lines.append(f"")
        summary_lines.append(f"=== LoRAs Used ===")
        for l in sorted(loras):
            summary_lines.append(f"  - {l}")
        summary_lines.append(f"")
        summary_lines.append(f"=== Positive Prompts ===")
        for p in positive_prompts:
            summary_lines.append(f"[{p['file']}]")
            summary_lines.append(f"  {p['text'][:200]}..." if len(p['text']) > 200 else f"  {p['text']}")
            summary_lines.append(f"")

        return (
            json.dumps(all_metadata, indent=2, ensure_ascii=False),
            "\n".join(summary_lines),
            len(files)
        )

    def _extract_values(self, workflow):
        result = {
            "positive_prompt": "",
            "negative_prompt": "",
            "seed": 0,
            "steps": 0,
            "cfg": 0.0,
            "model_name": "",
            "loras": []
        }
        try:
            for node_id, node_data in workflow.items():
                class_type = node_data.get("class_type", "")
                inputs = node_data.get("inputs", {})

                if "KSampler" in class_type:
                    result["seed"] = inputs.get("seed", inputs.get("noise_seed", 0))
                    result["steps"] = inputs.get("steps", 0)
                    result["cfg"] = inputs.get("cfg", 0.0)

                if class_type == "CLIPTextEncode":
                    text = inputs.get("text", "")
                    if text:
                        if not result["positive_prompt"]:
                            result["positive_prompt"] = text
                        elif text != result["positive_prompt"]:
                            result["negative_prompt"] = text

                if "PrimitiveString" in class_type:
                    text = inputs.get("value", inputs.get("text", ""))
                    if text and len(text) > 10:
                        if not result["positive_prompt"]:
                            result["positive_prompt"] = text
                        elif text != result["positive_prompt"]:
                            result["negative_prompt"] = text

                if "CheckpointLoader" in class_type:
                    result["model_name"] = inputs.get("ckpt_name", "")
                elif "UNETLoader" in class_type:
                    result["model_name"] = inputs.get("unet_name", "")

                if "LoraLoader" in class_type:
                    lora_name = inputs.get("lora_name", inputs.get("lora", ""))
                    if lora_name:
                        result["loras"].append(lora_name)
        except Exception:
            pass
        return result


class BatchMetadataToPromptList:
    CATEGORY = "Image Utilities"

    def __init__(self):
        pass

    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "all_metadata": ("STRING", {"default": ""}),
                "output_type": (["positive", "negative", "both"], {"default": "positive"}),
            },
        }

    RETURN_TYPES = ("STRING", "STRING", "INT")
    RETURN_NAMES = ("prompts_text", "prompts_json", "count")
    FUNCTION = "extract_prompts"
    OUTPUT_NODE = True

    def extract_prompts(self, all_metadata, output_type="positive"):
        try:
            data = json.loads(all_metadata)
        except json.JSONDecodeError:
            return ("Invalid JSON", "{}", 0)

        prompts = []
        for filename, file_data in data.items():
            if "extracted" in file_data:
                extracted = file_data["extracted"]
                entry = {"file": filename}

                if output_type == "positive" and extracted.get("positive_prompt"):
                    entry["prompt"] = extracted["positive_prompt"]
                    prompts.append(entry)
                elif output_type == "negative" and extracted.get("negative_prompt"):
                    entry["prompt"] = extracted["negative_prompt"]
                    prompts.append(entry)
                elif output_type == "both":
                    if extracted.get("positive_prompt"):
                        entry["positive"] = extracted["positive_prompt"]
                    if extracted.get("negative_prompt"):
                        entry["negative"] = extracted["negative_prompt"]
                    if entry.get("positive") or entry.get("negative"):
                        prompts.append(entry)

        lines = []
        for p in prompts:
            lines.append(f"[{p['file']}]")
            if "prompt" in p:
                lines.append(p["prompt"])
            elif "positive" in p or "negative" in p:
                if "positive" in p:
                    lines.append(f"Positive: {p['positive']}")
                if "negative" in p:
                    lines.append(f"Negative: {p['negative']}")
            lines.append("")

        return (
            "\n".join(lines),
            json.dumps(prompts, indent=2, ensure_ascii=False),
            len(prompts)
        )


class LoadImageWithMetadata:
    CATEGORY = "Image Utilities"

    def __init__(self):
        pass

    @classmethod
    def INPUT_TYPES(s):
        input_dir = folder_paths.get_input_directory()
        files = [f for f in os.listdir(input_dir) if f.lower().endswith(('.png', '.jpg', '.jpeg', '.webp'))]
        return {
            "required": {
                "image": (sorted(files),),
            },
        }

    RETURN_TYPES = ("IMAGE", "STRING", "STRING", "STRING")
    RETURN_NAMES = ("image", "workflow_prompt", "workflow_ui", "raw_metadata")
    FUNCTION = "load_image"
    OUTPUT_NODE = True

    def load_image(self, image):
        input_dir = folder_paths.get_input_directory()
        image_path = os.path.join(input_dir, image)

        img = Image.open(image_path)
        img_array = np.array(img).astype(np.float32) / 255.0
        image_tensor = torch.from_numpy(img_array)[None,]

        workflow_prompt = "No workflow prompt found."
        workflow_ui = "No workflow UI found."
        raw_metadata = "{}"

        try:
            metadata = img.info
            raw_metadata = json.dumps(metadata, indent=2, default=str)

            if "prompt" in metadata:
                try:
                    parsed = json.loads(metadata["prompt"])
                    workflow_prompt = json.dumps(parsed, indent=2)
                except json.JSONDecodeError:
                    workflow_prompt = metadata["prompt"]

            if "workflow" in metadata:
                try:
                    parsed = json.loads(metadata["workflow"])
                    workflow_ui = json.dumps(parsed, indent=2)
                except json.JSONDecodeError:
                    workflow_ui = metadata["workflow"]
        except Exception as e:
            workflow_prompt = f"Error reading metadata: {e}"

        return (image_tensor, workflow_prompt, workflow_ui, raw_metadata)


class ExtractPromptValues:
    CATEGORY = "Image Utilities"

    def __init__(self):
        pass

    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "workflow_prompt": ("STRING", {"default": ""}),
            },
        }

    RETURN_TYPES = ("STRING", "STRING", "INT", "INT", "FLOAT", "STRING")
    RETURN_NAMES = ("positive_prompt", "negative_prompt", "seed", "steps", "cfg", "model_name")
    FUNCTION = "extract"
    OUTPUT_NODE = True

    def extract(self, workflow_prompt):
        positive_prompt = ""
        negative_prompt = ""
        seed = 0
        steps = 0
        cfg = 0.0
        model_name = ""

        try:
            workflow = json.loads(workflow_prompt)
            for node_id, node_data in workflow.items():
                class_type = node_data.get("class_type", "")
                inputs = node_data.get("inputs", {})

                if "KSampler" in class_type:
                    seed = inputs.get("seed", inputs.get("noise_seed", 0))
                    steps = inputs.get("steps", 0)
                    cfg = inputs.get("cfg", 0.0)

                if class_type == "CLIPTextEncode":
                    text = inputs.get("text", "")
                    if text:
                        if not positive_prompt:
                            positive_prompt = text
                        elif text != positive_prompt:
                            negative_prompt = text

                if "PrimitiveString" in class_type:
                    text = inputs.get("value", inputs.get("text", ""))
                    if text and len(text) > 10:
                        if not positive_prompt:
                            positive_prompt = text
                        elif text != positive_prompt:
                            negative_prompt = text

                if "CheckpointLoader" in class_type:
                    model_name = inputs.get("ckpt_name", "")
                elif "UNETLoader" in class_type:
                    model_name = inputs.get("unet_name", "")
        except json.JSONDecodeError:
            pass
        except Exception as e:
            positive_prompt = f"Error: {e}"

        return (positive_prompt, negative_prompt, int(seed), int(steps), float(cfg), model_name)


# Register nodes
NODE_CLASS_MAPPINGS = {
    "BatchSimpleReadableMetadata": BatchSimpleReadableMetadata,
    "SimpleReadableMetadataKJ": SimpleReadableMetadataKJ,
    "BatchMetadataReader": BatchMetadataReader,
    "BatchMetadataToPromptList": BatchMetadataToPromptList,
    "LoadImageWithMetadata": LoadImageWithMetadata,
    "ExtractPromptValues": ExtractPromptValues,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "BatchSimpleReadableMetadata": "Batch Simple Readable Metadata",
    "SimpleReadableMetadataKJ": "Simple Readable Metadata (KJ)",
    "BatchMetadataReader": "Batch Read Metadata (Folder)",
    "BatchMetadataToPromptList": "Batch Metadata to Prompt List",
    "LoadImageWithMetadata": "Load Image (With Metadata)",
    "ExtractPromptValues": "Extract Prompt Values",
}
